type: postgresql
mode: standalone

cluster:
  instances: 1
  monitoring:
    enabled: true
    podMonitor:
      enabled: true
      labels: {}
      #   team-name: my-team

backups:
  enabled: false

poolers:
  - name: rw
    type: rw
    instances: 1
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
        relabelings:
          - targetLabel: type
            replacement: rw
  - name: ro
    type: ro
    instances: 1
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
        relabelings:
          - targetLabel: type
            replacement: ro
