type: postgresql
mode: standalone
version:
  major: "16"
  paradedb: "0.11.0"
cluster:
  instances: 1
backups:
  enabled: false
imageCatalog:
  create: true
  images:
    - major: 16
      image: my-custom-postgres-image:mytag
