type: postgresql
mode: standalone
version:
  major: "17"
  paradedb: "0.13.2"
cluster:
  instances: 1
backups:
  enabled: false
imageCatalog:
  create: true
  images:
    - major: 17
      image: my-custom-postgres-image:mytag
