apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster.fullname" . }}-backup-s3-creds
data:
  ACCESS_KEY_ID: {{ required ".Values.backups.s3.accessKey is required, but not specified." .Values.backups.s3.accessKey | b64enc }}
  ACCESS_SECRET_KEY: {{ required ".Values.backups.s3.secretKey is required, but not specified." .Values.backups.s3.secretKey | b64enc }}