name: release-publish

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Required for pushing the Helm charts to the gh-pages branch
      packages: write # Required for GHCR access
      id-token: write # Required for signing
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # important for fetching all history to run comparison against

      - name: Fetch history
        run: git fetch --prune

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Import PGP Private Key
        run: |
          echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --dearmor --output /tmp/keyring.gpg
          echo "${{ secrets.PGP_KEY_PASSPHRASE }}" > /tmp/passphrase-file.txt

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.16.2

      - name: Add chart dependencies
        run: |
          helm repo add cnpg-grafana-dashboard https://cloudnative-pg.github.io/grafana-dashboards

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_KEY: helm-charts+no-reply@cloudnative-pg.io
          CR_KEYRING: /tmp/keyring.gpg
          CR_PASSPHRASE_FILE: /tmp/passphrase-file.txt
          CR_SIGN: true
          CR_SKIP_EXISTING: true
          CR_GENERATE_RELEASE_NOTES: true
          CR_RELEASE_NAME_TEMPLATE: "{{ .Name }}-v{{ .Version }}"

      - name: Securely delete the PGP key and passphrase
        if: always()
        run: shred --remove=wipesync /tmp/keyring.gpg /tmp/passphrase-file.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install sigstore/cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0

      - name: Push charts to GHCR
        env:
          COSIGN_EXPERIMENTAL: 1
        # when filling gaps with previously released charts, cr would create
        # nothing in .cr-release-packages/, and the original globbing character
        # would be preserved, causing a non-zero exit. Set nullglob to fix this
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/"${GITHUB_REPOSITORY}"
            file=${pkg##*/}
            name=${file%-*}
            version=${file%.*}
            version=${version##*-}
            cosign sign --yes ghcr.io/"${GITHUB_REPOSITORY}"/"${name}":"${version}"
          done
