##
# Create a PR for a release when a commit is pushed on a release/*-v* branch to support the releases of both the
# operator and cluster charts
name: release-pr

on:
  push:
    branches:
      - release/*-v*

permissions: read-all

jobs:
  create-pull-request:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create Pull Request
        id: create-pr
        env:
          GH_TOKEN: ${{ secrets.REPO_GHA_PAT }}
        run: |
          TAG="${GITHUB_REF##*/}"
          TITLE="Release ${TAG}"
          BODY="Automated PR. Will trigger the ${TAG} release when approved."
          LABEL=release
          ASSIGNEE=${{ github.actor }}
          gh pr create --title "${TITLE}" --body "${BODY}" --label "${LABEL}" --assignee "${ASSIGNEE}" ||
          gh pr edit --title "${TITLE}" --body "${BODY}" --add-label "${LABEL}"
