name: tests-operator

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  deploy_operator:
    name: Deploy the operator in cluster-wide mode
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup kind
        uses: ./.github/actions/setup-kind

      - name: Deploy the operator
        uses: ./.github/actions/deploy-operator

      - name: Deploy a cluster
        uses: ./.github/actions/deploy-cluster

      - name: Verify that the cluster is ready
        uses: ./.github/actions/verify-cluster-ready
        with:
          cluster-name: cluster-example
          ready-instances: '3'

  deploy_operator_single_namespace:
    name: Deploy the operator in single-namespace mode
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Setup kind
        uses: ./.github/actions/setup-kind

      - name: Deploy the operator
        uses: ./.github/actions/deploy-operator
        with:
          namespace: 'single-install'
          cluster-wide: 'false'

      - name: Deploy a cluster
        uses: ./.github/actions/deploy-cluster
        with:
          namespace: 'single-install'

      - name: Verify that the cluster is ready
        uses: ./.github/actions/verify-cluster-ready
        with:
          namespace: 'single-install'
          cluster-name: 'cluster-example'
          ready-instances: '3'
