name: tests-cluster-standalone

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  test-cluster-standalone:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup kind
        uses: ./.github/workflows/reusable/setup-kind

      - name: Deploy the operator
        uses: ./.github/workflows/reusable/deploy-operator

      - name: Deploy a standalone cluster
        run: |
          helm upgrade --install \
            --values charts/cluster/examples/basic.yaml \
            --namespace database \
            --wait \
            database ./charts/cluster

      - name: Verify that the cluster is ready
        uses: ./.github/workflows/reusable/verify-ready-instances
        with:
          cluster-name: database-cluster
          ready-instances: 1
