name: tests-operator

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'

permissions: read-all

jobs:
  deploy_operator:
    name: Deploy the operator in cluster-wide mode
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup kind
        uses: ./.github/actions/setup-kind

      - name: Deploy the operator
        uses: ./.github/actions/deploy-operator

      - name: Deploy a cluster
        uses: ./.github/actions/deploy-cluster

      - name: Verify that the cluster is ready
        uses: ./.github/actions/verify-cluster-ready
        with:
          cluster-name: cluster-example
          ready-instances: '3'

  deploy_operator_single_namespace:
    name: Deploy the operator in single-namespace mode
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup kind
        uses: ./.github/actions/setup-kind

      - name: Deploy the operator
        uses: ./.github/actions/deploy-operator
        with:
          namespace: 'single-install'
          cluster-wide: 'false'

      - name: Deploy a cluster
        uses: ./.github/actions/deploy-cluster
        with:
          namespace: 'single-install'

      - name: Verify that the cluster is ready
        uses: ./.github/actions/verify-cluster-ready
        with:
          namespace: 'single-install'
          cluster-name: 'cluster-example'
          ready-instances: '3'

      - name: Create a separate namespace
        run: kubectl create ns test-ignore

      - name: Deploy a cluster in 'test-ignore'
        uses: ./.github/actions/deploy-cluster
        with:
          namespace: 'test-ignore'

      - name: Verify the cluster in 'test-ignore' is being ignored
        run: |
          kubectl -n test-ignore get pods 2>&1 >/dev/null | grep 'No resources found'
